In [1]:
import torch 
import numpy as np

Directly from data

Tensors can be created directly from data. The data type is automatically inferred.

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [7]:
#from numpy to tensor
data = [[1, 2, 3], [3, 1, 2]]
np_array = np.array(data)
x_tensor = torch.from_numpy(np_array)
print(x_tensor)
#from tensor into numpy 
back_to_numpy = x_tensor.numpy()
print(back_to_numpy)

tensor([[1, 2, 3],
        [3, 1, 2]], dtype=torch.int32)
[[1 2 3]
 [3 1 2]]


<h5  style="color:blue">A change in the tensor reflects in the NumPy array.</h5>

In [11]:
data = [1, 2, 3, 1, 2]
np_array = np.array(data)
x_tensor = torch.from_numpy(np_array)
x_tensor.add_(1)
print(x_tensor)
print(np_array)

tensor([2, 3, 4, 2, 3], dtype=torch.int32)
[2 3 4 2 3]


<h5>matmul does the matrix multiplication of the tensor</h5>

In [16]:
#creating a random shape tensor array
shape = (2, 3)
rand_tensor = torch.rand(shape)
one_tensor = torch.ones(shape)
zeroes_tensor = torch.zeros(shape)
print(rand_tensor)
print(one_tensor)
print(zeroes_tensor)

tensor([[0.6836, 0.1104, 0.0028],
        [0.5328, 0.5642, 0.5521]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
